%%% DDAR Facts simplified for essential theorems
%%% Generated by DDAR Adapter

:- discontiguous fact/3.
:- discontiguous fact_period/3.
:- discontiguous fact_confidence/3.


%%% Facts for XL Axiata
fact(xl_axiata, at, 1.178737536265039e-08).
fact_period(xl_axiata, at, fy(2024)).
fact_confidence(xl_axiata, at, 0.85).

fact(xl_axiata, at, 1.178737536265039e-08).
fact_period(xl_axiata, at, fy(2024)).
fact_confidence(xl_axiata, at, 0.85).

fact(xl_axiata, borrowings, 3187407.0000).
fact_period(xl_axiata, borrowings, fy(2024)).
fact_confidence(xl_axiata, borrowings, 0.95).

fact(xl_axiata, cash, 1463736.0000).
fact_period(xl_axiata, cash, fy(2024)).
fact_confidence(xl_axiata, cash, 0.95).

fact(xl_axiata, cash_ratio, 0.061507903741426576).
fact_period(xl_axiata, cash_ratio, fy(2024)).
fact_confidence(xl_axiata, cash_ratio, 0.85).

fact(xl_axiata, current_assets, 8562510.0000).
fact_period(xl_axiata, current_assets, fy(2024)).
fact_confidence(xl_axiata, current_assets, 0.95).

fact(xl_axiata, current_liabilities, 23797527.0000).
fact_period(xl_axiata, current_liabilities, fy(2024)).
fact_confidence(xl_axiata, current_liabilities, 0.95).

fact(xl_axiata, current_ratio, 0.3598067143699427).
fact_period(xl_axiata, current_ratio, fy(2024)).
fact_confidence(xl_axiata, current_ratio, 0.85).

fact(xl_axiata, debt_to_assets, 0.037571162742539396).
fact_period(xl_axiata, debt_to_assets, fy(2024)).
fact_confidence(xl_axiata, debt_to_assets, 0.85).

fact(xl_axiata, debt_to_equity, 0.1250290124804758).
fact_period(xl_axiata, debt_to_equity, fy(2024)).
fact_confidence(xl_axiata, debt_to_equity, 0.85).

fact(xl_axiata, fl, 3.3277919381215617).
fact_period(xl_axiata, fl, fy(2024)).
fact_confidence(xl_axiata, fl, 0.85).

fact(xl_axiata, inventory, 200354.0000).
fact_period(xl_axiata, inventory, fy(2024)).
fact_confidence(xl_axiata, inventory, 0.95).

fact(xl_axiata, invested_capital, 27217010.0000).
fact_period(xl_axiata, invested_capital, fy(2024)).
fact_confidence(xl_axiata, invested_capital, 0.85).

fact(xl_axiata, non_current_assets, 76274018.0000).
fact_period(xl_axiata, non_current_assets, fy(2024)).
fact_confidence(xl_axiata, non_current_assets, 0.95).

fact(xl_axiata, revenue, 1.0000).
fact_period(xl_axiata, revenue, fy(2024)).
fact_confidence(xl_axiata, revenue, 0.95).

fact(xl_axiata, tax_expense, 523151.0000).
fact_period(xl_axiata, tax_expense, fy(2024)).
fact_confidence(xl_axiata, tax_expense, 0.95).

fact(xl_axiata, total_assets, 84836528.0000).
fact_period(xl_axiata, total_assets, fy(2024)).
fact_confidence(xl_axiata, total_assets, 0.95).

fact(xl_axiata, total_debt, 3187407.0000).
fact_period(xl_axiata, total_debt, fy(2024)).
fact_confidence(xl_axiata, total_debt, 0.95).

fact(xl_axiata, equity_value, 25493339.0000).
fact_period(xl_axiata, equity_value, fy(2024)).
fact_confidence(xl_axiata, equity_value, 0.95).


%%% End of facts
