%%% DDAR Facts simplified for essential theorems
%%% Generated by DDAR Adapter

:- discontiguous fact/3.
:- discontiguous fact_period/3.
:- discontiguous fact_confidence/3.


%%% Facts for Axiata
fact(axiata, operating_margin, 0.04030201821035188).
fact_period(axiata, operating_margin, fy(2023)).
fact_confidence(axiata, operating_margin, 0.85).

fact(axiata, at, 0.30037410565388134).
fact_period(axiata, at, fy(2024)).
fact_confidence(axiata, at, 0.85).

fact(axiata, at, 0.30037410565388134).
fact_period(axiata, at, fy(2024)).
fact_confidence(axiata, at, 0.85).

fact(axiata, cash, 4860.4400000000005).
fact_period(axiata, cash, fy(2024)).
fact_confidence(axiata, cash, 0.95).

fact(axiata, cash_ratio, 0.2986145110934157).
fact_period(axiata, cash_ratio, fy(2024)).
fact_confidence(axiata, cash_ratio, 0.85).

fact(axiata, current_assets, 10434.137).
fact_period(axiata, current_assets, fy(2024)).
fact_confidence(axiata, current_assets, 0.95).

fact(axiata, current_liabilities, 16276.637).
fact_period(axiata, current_liabilities, fy(2024)).
fact_confidence(axiata, current_liabilities, 0.95).

fact(axiata, current_ratio, 0.0262993516412512).
fact_period(axiata, current_ratio, fy(2024)).
fact_confidence(axiata, current_ratio, 0.85).

fact(axiata, current_ratio, 0.6410499294172377).
fact_period(axiata, current_ratio, fy(2024)).
fact_confidence(axiata, current_ratio, 0.85).

fact(axiata, debt_to_assets, 0.31189123944268116).
fact_period(axiata, debt_to_assets, fy(2024)).
fact_confidence(axiata, debt_to_assets, 0.85).

fact(axiata, debt_to_equity, 0.8409544185371868).
fact_period(axiata, debt_to_equity, fy(2024)).
fact_confidence(axiata, debt_to_equity, 0.85).

fact(axiata, debt_to_equity, 0.8409626266915858).
fact_period(axiata, debt_to_equity, fy(2024)).
fact_confidence(axiata, debt_to_equity, 0.85).

fact(axiata, debt_to_equity, 1.0942757042419666).
fact_period(axiata, debt_to_equity, fy(2024)).
fact_confidence(axiata, debt_to_equity, 0.85).

fact(axiata, ebit, 2564.475).
fact_period(axiata, ebit, fy(2024)).
fact_confidence(axiata, ebit, 0.95).

fact(axiata, fl, 3.5085169631482094).
fact_period(axiata, fl, fy(2024)).
fact_confidence(axiata, fl, 0.85).

fact(axiata, interest_coverage, 7.804862831508275).
fact_period(axiata, interest_coverage, fy(2024)).
fact_confidence(axiata, interest_coverage, 0.85).

fact(axiata, interest_expense, 1404.084).
fact_period(axiata, interest_expense, fy(2024)).
fact_confidence(axiata, interest_expense, 0.95).

fact(axiata, inventory, 122.663).
fact_period(axiata, inventory, fy(2024)).
fact_confidence(axiata, inventory, 0.95).

fact(axiata, net_income, 1598859.0).
fact_period(axiata, net_income, fy(2024)).
fact_confidence(axiata, net_income, 0.95).

fact(axiata, net_income, 1598.859).
fact_period(axiata, net_income, fy(2024)).
fact_confidence(axiata, net_income, 0.95).

fact(axiata, npm, 0.002997840172786177).
fact_period(axiata, npm, fy(2024)).
fact_confidence(axiata, npm, 0.85).

fact(axiata, npm, 0.07158658686647726).
fact_period(axiata, npm, fy(2024)).
fact_confidence(axiata, npm, 0.85).

fact(axiata, npm, 0.07158658686647726).
fact_period(axiata, npm, fy(2024)).
fact_confidence(axiata, npm, 0.85).

fact(axiata, payables, 1198.032).
fact_period(axiata, payables, fy(2024)).
fact_confidence(axiata, payables, 0.95).

fact(axiata, receivables, 916.597).
fact_period(axiata, receivables, fy(2024)).
fact_confidence(axiata, receivables, 0.95).

fact(axiata, revenue, 22334.617000000002).
fact_period(axiata, revenue, fy(2024)).
fact_confidence(axiata, revenue, 0.95).

fact(axiata, roa, 0.021502757006831998).
fact_period(axiata, roa, fy(2024)).
fact_confidence(axiata, roa, 0.85).

fact(axiata, roe, 1.2583080514345565e-05).
fact_period(axiata, roe, fy(2024)).
fact_confidence(axiata, roe, 0.85).

fact(axiata, roe, 0.07544278771292408).
fact_period(axiata, roe, fy(2024)).
fact_confidence(axiata, roe, 0.85).

fact(axiata, tax_expense, 78.44200000000001).
fact_period(axiata, tax_expense, fy(2024)).
fact_confidence(axiata, tax_expense, 0.95).

fact(axiata, total_assets, 74356.0).
fact_period(axiata, total_assets, fy(2024)).
fact_confidence(axiata, total_assets, 0.95).

fact(axiata, total_debt, 23191.0).
fact_period(axiata, total_debt, fy(2024)).
fact_confidence(axiata, total_debt, 0.95).

fact(axiata, total_debt, 23190.985).
fact_period(axiata, total_debt, fy(2024)).
fact_confidence(axiata, total_debt, 0.95).

fact(axiata, total_equity, 21193.0).
fact_period(axiata, total_equity, fy(2024)).
fact_confidence(axiata, total_equity, 0.95).

fact(axiata, total_equity, 21193.214).
fact_period(axiata, total_equity, fy(2024)).
fact_confidence(axiata, total_equity, 0.95).

fact(axiata, current_assets, 10499.362000000001).
fact_period(axiata, current_assets, fy(2025)).
fact_confidence(axiata, current_assets, 0.95).

fact(axiata, current_liabilities, 16913.792).
fact_period(axiata, current_liabilities, fy(2025)).
fact_confidence(axiata, current_liabilities, 0.95).

fact(axiata, current_ratio, 0.6207574268384051).
fact_period(axiata, current_ratio, fy(2025)).
fact_confidence(axiata, current_ratio, 0.85).

fact(axiata, current_ratio, 0.6207574268384051).
fact_period(axiata, current_ratio, fy(2025)).
fact_confidence(axiata, current_ratio, 0.85).

fact(axiata, ebit, 456.534).
fact_period(axiata, ebit, fy(2025)).
fact_confidence(axiata, ebit, 0.95).

fact(axiata, ebitda, 2.4541999999999997).
fact_period(axiata, ebitda, fy(2025)).
fact_confidence(axiata, ebitda, 0.95).

fact(axiata, ebitda_margin, 0.48226532256479787).
fact_period(axiata, ebitda_margin, fy(2025)).
fact_confidence(axiata, ebitda_margin, 0.85).

fact(axiata, ebitda_margin, 0.0004822656068692292).
fact_period(axiata, ebitda_margin, fy(2025)).
fact_confidence(axiata, ebitda_margin, 0.85).

fact(axiata, net_income, 0.3085).
fact_period(axiata, net_income, fy(2025)).
fact_confidence(axiata, net_income, 0.95).

fact(axiata, npm, 0.06062213837961053).
fact_period(axiata, npm, fy(2025)).
fact_confidence(axiata, npm, 0.85).

fact(axiata, npm, 6.06221741174954e-05).
fact_period(axiata, npm, fy(2025)).
fact_confidence(axiata, npm, 0.85).

fact(axiata, npm, 6.06221741174954e-05).
fact_period(axiata, npm, fy(2025)).
fact_confidence(axiata, npm, 0.85).

fact(axiata, operating_margin, 0.15637957122364363).
fact_period(axiata, operating_margin, fy(2025)).
fact_confidence(axiata, operating_margin, 0.85).

fact(axiata, receivables, 3.396).
fact_period(axiata, receivables, fy(2025)).
fact_confidence(axiata, receivables, 0.95).

fact(axiata, revenue, 5088.897).
fact_period(axiata, revenue, fy(2025)).
fact_confidence(axiata, revenue, 0.95).

fact(axiata, roe, 1.143518630920929e-05).
fact_period(axiata, roe, fy(2025)).
fact_confidence(axiata, roe, 0.85).

fact(axiata, roe, 1.143518630920929e-05).
fact_period(axiata, roe, fy(2025)).
fact_confidence(axiata, roe, 0.85).

fact(axiata, total_equity, 26978.135000000002).
fact_period(axiata, total_equity, fy(2025)).
fact_confidence(axiata, total_equity, 0.95).


%%% End of facts
