# Minimal Causal Rules Configuration
# Simple rules with confidence only

causal_rules:
  # Market position implications
  - antecedent: market_leader
    consequent: pricing_power
    confidence: 0.8
    
  - antecedent: market_leader
    consequent: strong_brand
    confidence: 0.75
    
  - antecedent: weak_position
    consequent: no_pricing_power
    confidence: 0.9
    
  # Competitive advantage chains
  - antecedent: strong_moat
    consequent: pricing_power
    confidence: 0.7
    
  - antecedent: network_effects
    consequent: strong_moat
    confidence: 0.85
    
  - antecedent: switching_costs
    consequent: pricing_power
    confidence: 0.65
    
  # Brand implications  
  - antecedent: strong_brand
    consequent: pricing_power
    confidence: 0.7
    
  # Operational advantages
  - antecedent: economies_of_scale
    consequent: strong_moat
    confidence: 0.6
    
  - antecedent: economies_of_scale
    consequent: cost_advantage
    confidence: 0.9
    
  # Technology leadership
  - antecedent: technological_supremacy
    consequent: strong_moat
    confidence: 0.8
    
  - antecedent: technological_supremacy
    consequent: competitive_advantage
    confidence: 0.85
    
  - antecedent: competitive_advantage
    consequent: pricing_power
    confidence: 0.8
    
  - antecedent: first_mover_advantage
    consequent: market_leader
    confidence: 0.6
    
  # Financial implications
  - antecedent: pricing_power
    consequent: high_margins
    confidence: 0.9
    
  - antecedent: no_pricing_power
    consequent: commoditization
    confidence: 0.8
    
  - antecedent: high_margins
    consequent: strong_cash_flow
    confidence: 0.85
    
  - antecedent: strong_cash_flow
    consequent: investment_capacity
    confidence: 0.9
    
  - antecedent: cost_advantage
    consequent: high_margins
    confidence: 0.8
    
  # Negative spirals
  # Removed circular rule: commoditization -> no_pricing_power (creates cycle)
  - antecedent: commoditization
    consequent: low_returns
    confidence: 0.9

# Settings for reasoning
settings:
  min_confidence_to_derive: 0.5
  max_depth: 5