# Minimal Extraction Rules Configuration
# Properties with patterns and confidence only

properties:
  # Market position
  market_leader:
    patterns:
      - "market leader"
      - "leading position"
      - "dominant player"
      - "largest.*market share"
    type: positive
    confidence: 0.9

  weak_position:
    patterns:
      - "weak.*position"
      - "vulnerable"
      - "struggling"
      - "losing ground"
    type: negative
    confidence: 0.85

  # Pricing
  pricing_power:
    patterns:
      - "(?<!no )pricing power"
      - "strong pricing"
      - "premium pricing"
      - "raise.*prices"
    type: positive
    confidence: 0.8

  no_pricing_power:
    patterns:
      - "no pricing power"
      - "unable.*raise prices"
      - "cannot.*raise prices"
      - "price pressure"
    type: negative
    confidence: 0.9

  # Competitive advantage
  strong_moat:
    patterns:
      - "competitive advantage"
      - "barrier.*entry"
      - "moat"
      - "defensible position"
    type: positive
    confidence: 0.85

  network_effects:
    patterns:
      - "network effect"
      - "platform.*effect"
      - "viral growth"
    type: positive
    confidence: 0.85

  switching_costs:
    patterns:
      - "switching cost"
      - "lock.*in"
      - "sticky.*customer"
    type: positive
    confidence: 0.8

  # Brand
  strong_brand:
    patterns:
      - "strong brand"
      - "brand recognition"
      - "brand loyalty"
      - "premium brand"
    type: positive
    confidence: 0.8

  # Market dynamics
  commoditization:
    patterns:
      - "commoditiz"
      - "undifferentiated"
      - "no.*differentiation"
    type: negative
    confidence: 0.9

  regulation:
    patterns:
      - "regulat.*prevent"
      - "government.*control"
      - "price.*cap"
      - "regulatory.*constraint"
    type: negative
    confidence: 0.95
    negates: pricing_power  # When found, emit no_pricing_power

  # Technology
  technological_supremacy:
    patterns:
      - "technological supremacy"
      - "tech.*leader"
      - "technological advantage"
    type: positive
    confidence: 0.85

  first_mover_advantage:
    patterns:
      - "first.?mover"
      - "pioneer"
      - "first to market"
    type: positive
    confidence: 0.8

  economies_of_scale:
    patterns:
      - "economies of scale"
      - "scale advantage"
      - "cost advantage.*scale"
    type: positive
    confidence: 0.8

# Extraction settings
settings:
  min_confidence_to_assert: 0.5