"""
Test Section definitions 
Contains descriptions of select test sections
"""

sections = [
    {
        "number": 1,
        "title": "Operating Footprint",
        "type": "analytical",
        "specs": "Extract and analyze the company's operational presence and scale. Focus on understanding how the company's physical and human resources are distributed and how they support its business model.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Employee distribution across locations and functions\\n"
                "b. Main operating assets, their strategic importance and their ownership (owned or leased)\\n"
                "c. Geographic footprint and alignment with business strategy\\n"
                "d. Any significant changes or trends in the operating footprint\\n"
                "e. How the operating structure supports competitive positioning\\n"
                "f. How the operating structure drives unit economics\\n"
                "\\n"
                "Extract operating data points such as capacity, square footage, number of customers, etc., but NOT financial data\\n"
                "Look for insights that connect the operating footprint to business performance and strategic objectives.\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 2,
        "title": "Products and Services",
        "type": "analytical",
        "specs": "Extract and analyze the company's product and service offerings. Focus on understanding the value proposition of each product or service from the customer's perspective.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. List of main product/service categories\\n"
                "b. Individual products within each category\\n"
                "c. Value proposition for each product\\n"
                "d. Market positioning and competitive differentiation\\n"
                "e. Product lifecycle stage\\n"
                "f. Any data points such as market share, growth rates, etc., but NOT financial data\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 3,
        "title": "Key Customers",
        "type": "analytical",
        "specs": "Extract and analyze the company's customer relationships. Focus on understanding the key customers and their contribution to the company's revenue.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. List of largest customers\\n"
                "b. Position in the value chain: whether customer is an OEM, Tier 1, or Tier 2 supplier\\n"
                "c. Relationship strength and duration\\n"
                "d. Products purchased by each key customer and associated metrics\\n"
                "e. Customer segmentation by industry and geography\\n"
                "f. Customer positioning (premium, mid-market, value segments)\\n"
                "g. Revenue contribution and customer concentration\\n"
                "h. Purchase patterns and contract terms\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 4,
        "title": "Key Suppliers",
        "type": "analytical",
        "specs": "Extract and analyze the company's supplier relationships.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. List of largest suppliers and supplier concentration\\n"
                "b. Materials or components provided by each key supplier\\n"
                "c. Supplier's position in the value chain (B2B, B2C, B2B2C) and margin capture\\n"
                "d. COGS contribution\\n"
                "e. Relationship duration\\n"
                "f. Supplier segmentation by industry and geography\\n"
                "h. Pricing trends\\n"
                "k. Supplier performance metrics (quality, on-time delivery)\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 5,
        "title": "Key Competitors",
        "type": "analytical",
        "specs": "Extract and analyze the company's competitive landscape.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. List of key competitors and their recent strategic moves\\n"
                "b. Market structure and competitive dynamics\\n"
                "c. Product comparisons and areas of competition\\n"
                "d. Market share trends and competitive strategies\\n"
                "e. Current positioning and recent changes\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 6,
        "title": "Operational KPIs",
        "type": "analytical",
        "specs": "Extract and analyze operational KPIs (not financial KPIs)that directly impact cash flow generation.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Market share metrics and trends (by product, region, customer segment)\\n"
                "b. Volume metrics and trends (units sold, customers served)\\n"
                "c. Pricing metrics and trends (average selling price, price trends)\\n"
                "d. Customer metrics and trends (retention, acquisition cost, lifetime value)\\n"
                "e. Operational efficiency metrics and trends (capacity utilization, cycle times)\\n"
                "f. Unit economics and business impact\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 7,
        "title": "Summary Financials (Consolidated)",
        "type": "analytical",
        "specs": "Extract and analyze the company's consolidated financial performance, both annually and interim periods.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Financial Metrics:\\n"
                "   - Revenue\\n"
                "   - EBITDA and margin\\n"
                "   - Operating Income and margin\\n"
                "   - Net Income and margin\\n"
                "   - Capex and % of revenue\\n"
                "   - Cash conversion (EBITDA / (EBITDA/Capex))\\n"
                "\\n"
                "b. Time Periods:\\n"
                "   - Last 3 financial years\\n"
                "   - 5 most recent interim periods\\n"
                "   - Any forecasts or guidance\\n"
                "\\n"
                "c. Additional Data:\\n"
                "   - GAAP and non-GAAP measures\\n"
                "   - One-time items\\n"
                "   - Industry comparisons\\n"
                "\\n"
                "Analysis Requirements:\\n"
                "a. Trend Analysis:\\n"
                "   - Revenue growth\\n"
                "   - Margin evolution\\n"
                "   - Cash flow generation\\n"
                "\\n"
                "b. Performance Assessment:\\n"
                "   - Achievement vs. guidance\\n"
                "   - Industry comparison\\n"
                "   - Key drivers of performance\\n"
                "\\n"
                "Output Format:\\n"
                "a. Financial Summary:\\n"
                "   - Key metrics in table format, if possible\\n" 
                "   - Key recent trends\\n"
                "   - Margin analysis\\n"
                "   - Cash flow assessment\\n"
                "\\n"
                "b. MDNA highlighting key recent trends:\\n"
                "   - 2 key achievements\\n"
                "   - 2 key challenges\\n"
                "   - 2 areas of disconnect between management statements and actual performance\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 8,
        "title": "Summary Financials (Segment)",
        "type": "analytical",
        "specs": "Extract and analyze financial performance by business segment.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Segment Data:\\n"
                "   - Segment names and definitions\\n"
                "   - Revenue by segment\\n"
                "   - Operating income by segment\\n"
                "   - EBITDA by segment\\n"
                "   - Assets by segment\\n"
                "\\n"
                "b. Time Periods:\\n"
                "   - Last 3 financial years\\n"
                "   - 5 most recent quarters\\n"
                "   - Any segment-specific forecasts or guidance\\n"
                "\\n"
                "c. Additional Data:\\n"
                "   - One-time items by segment\\n"
                "   - Segment-specific metrics\\n"
                "   - Inter-segment transactions\\n"
                "\\n"
                "Analysis Requirements:\\n"
                "1. Segment Analysis:\\n"
                "   - Growth trends by segment\\n"
                "   - Margin evolution by segment\\n"
                "   - Asset efficiency by segment\\n"
                "\\n"
                "b. Contribution Analysis:\\n"
                "   - Segment performance comparison\\n"
                "   - Segment contribution to overall results\\n"
                "   - Strategic importance by segment\\n"
                "\\n"
                "Output Format:\\n"
                 "a. Financial Summary by segment:\\n"
                "   - Key metrics by segment in table format, if possible\\n" 
                "   - Key recent trends by segment\\n"
                "   - Margin analysis by segment\\n"
                "   - Cash flow assessment by segment\\n"
                "\\n"
                "b. MDNA highlighting key recent trends by segment:\\n"
                "   - 2 key achievements by segment\\n"
                "   - 2 key challenges by segment\\n"
                "   - 2 areas of disconnect between management statements and actual performance by segment\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 9,
        "title": "Balance Sheet (Most Recent)",
        "type": "analytical",
        "specs": "Extract and analyze the company's most recent balance sheet.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Asset Analysis:\\n"
                "   - Composition of assets (current vs. non-current)\\n"
                "   - Key asset categories (cash, receivables, inventory, PPE, intangibles)\\n"
                "   - Asset quality and liquidity\\n"
                "\\n"
                "b. Liability Analysis:\\n"
                "   - Composition of liabilities (current vs. non-current)\\n"
                "   - Key liability categories (payables, debt, deferred revenue)\\n"
                "   - Maturity profile of debt\\n"
                "\\n"
                "c. Equity Analysis:\\n"
                "   - Components of equity (common stock, retained earnings, etc.)\\n"
                "   - Changes in equity over time\\n"
                "\\n"
                "d. Financial Ratios:\\n"
                "   - Current ratio, quick ratio\\n"
                "   - Debt-to-equity, debt-to-assets\\n"
                "   - Working capital analysis\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 10,
        "title": "Cash Flow Statement (Most Recent)",
        "type": "analytical",
        "specs": "Extract and analyze the company's most recent cash flow statement.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Cash from Operations (CFO):\\n"
                "   - Key drivers of CFO (net income, D&A, working capital changes)\\n"
                "   - Quality of earnings (CFO vs. net income)\\n"
                "\\n"
                "b. Cash from Investing (CFI):\\n"
                "   - Capital expenditures (maintenance vs. growth)\\n"
                "   - Acquisitions and divestitures\\n"
                "\\n"
                "c. Cash from Financing (CFF):\\n"
                "   - Debt issuance and repayment\\n"
                "   - Equity issuance and buybacks\\n"
                "   - Dividend payments\\n"
                "\\n"
                "d. Free Cash Flow (FCF):\\n"
                "   - FCF to the firm (FCFF) and to equity (FCFE)\\n"
                "   - FCF conversion and trends\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 11,
        "title": "Capital Structure (Current)",
        "type": "analytical",
        "specs": "Extract and analyze the company's current capital structure.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Debt Analysis:\\n"
                "   - Total debt and net debt\\n"
                "   - Debt maturity profile\\n"
                "   - Interest rate exposure (fixed vs. floating)\\n"
                "   - Debt covenants and credit ratings\\n"
                "\\n"
                "b. Equity Analysis:\\n"
                "   - Shares outstanding and market capitalization\\n"
                "   - Shareholder equity trends\\n"
                "\\n"
                "c. Capital Allocation:\\n"
                "   - Dividend policy and payout ratio\\n"
                "   - Share buyback programs\\n"
                "   - Reinvestment strategy\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 12,
        "title": "Corporate Strategy",
        "type": "analytical",
        "specs": "Extract and analyze the company's stated corporate strategy.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Vision and Mission:\\n"
                "   - Company's long-term vision\\n"
                "   - Mission statement and core values\\n"
                "\\n"
                "b. Strategic Priorities:\\n"
                "   - Key pillars of the corporate strategy\\n"
                "   - Growth drivers and target markets\\n"
                "\\n"
                "c. Competitive Advantage:\\n"
                "   - How the company plans to win in the market\\n"
                "   - Sources of sustainable competitive advantage\\n"
                "\\n"
                "d. Strategy Evolution:\\n"
                "   - Recent changes or shifts in strategy\\n"
                "   - Alignment with market trends and challenges\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 13,
        "title": "Strategic Initiatives and Progress",
        "type": "analytical",
        "specs": "Extract and analyze the company's strategic initiatives and their progress.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Key Initiatives:\\n"
                "   - Description of major strategic projects\\n"
                "   - Alignment with corporate strategy\\n"
                "\\n"
                "b. Progress and Milestones:\\n"
                "   - Status of each initiative (planned, in-progress, completed)\\n"
                "   - Key milestones achieved and upcoming\\n"
                "\\n"
                "c. Resource Allocation:\\n"
                "   - Investment and resources dedicated to each initiative\\n"
                "   - Expected returns and timelines\\n"
                "\\n"
                "d. Performance Measurement:\\n"
                "   - KPIs used to track progress and success\\n"
                "   - Actual performance vs. targets\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 14,
        "title": "Strategic Constraints",
        "type": "analytical",
        "specs": "Extract and analyze the company's strategic constraints.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Internal Constraints:\\n"
                "   - Resource limitations (financial, human, technological)\\n"
                "   - Organizational or cultural barriers\\n"
                "\\n"
                "b. External Constraints:\\n"
                "   - Market or competitive pressures\\n"
                "   - Regulatory or legal hurdles\\n"
                "   - Macroeconomic factors\\n"
                "\\n"
                "c. Impact on Strategy:\\n"
                "   - How these constraints affect strategic execution\\n"
                "   - Mitigation plans and their effectiveness\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 15,
        "title": "Management & Board",
        "type": "analytical",
        "specs": "Extract and analyze the company's management and board of directors.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Management Team:\\n"
                "   - Key executives and their backgrounds\\n"
                "   - Tenure and experience\\n"
                "   - Compensation and incentives\\n"
                "\\n"
                "b. Board of Directors:\\n"
                "   - Board composition and independence\\n"
                "   - Director skills and experience\\n"
                "   - Committee structure and effectiveness\\n"
                "\\n"
                "c. Succession Planning:\\n"
                "   - Plans for key leadership roles\\n"
                "   - Bench strength of the management team\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 16,
        "title": "Corporate Governance",
        "type": "analytical",
        "specs": "Extract and analyze the company's corporate governance practices.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Board Structure & Practices:\\n"
                "   - Board independence and oversight\\n"
                "   - Executive compensation policies\\n"
                "   - Shareholder rights and voting\\n"
                "\\n"
                "b. Ethics & Compliance:\\n"
                "   - Code of conduct and ethical policies\\n"
                "   - Whistleblower programs and anti-corruption measures\\n"
                "\\n"
                "c. Transparency & Disclosure:\\n"
                "   - Quality and timeliness of financial reporting\\n"
                "   - Disclosure of non-financial information\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 17,
        "title": "Shareholders & Ownership",
        "type": "analytical",
        "specs": "Extract and analyze the company's shareholder base and ownership structure.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Major Shareholders:\\n"
                "   - List of top institutional and individual shareholders\\n"
                "   - Ownership concentration and potential influence\\n"
                "\\n"
                "b. Shareholder Activism:\\n"
                "   - History of activist campaigns\\n"
                "   - Key activist investors and their agendas\\n"
                "\\n"
                "c. Insider & Related Party Transactions:\\n"
                "   - Significant transactions with insiders or related parties\\n"
                "   - Potential conflicts of interest\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 18,
        "title": "Management Discussion & Analysis (MD&A)",
        "type": "analytical",
        "specs": "Extract and analyze the Management Discussion & Analysis (MD&A) section of the company's financial reports.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Key Themes & Narratives:\\n"
                "   - Management's perspective on performance\\n"
                "   - Explanation of key trends and events\\n"
                "\\n"
                "b. Consistency & Candor:\\n"
                "   - Consistency of messaging over time\\n"
                "   - Candor in discussing challenges and risks\\n"
                "\\n"
                "c. Critical Accounting Policies:\\n"
                "   - Key accounting estimates and judgments\\n"
                "   - Potential impact on financial results\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 19,
        "title": "Risk Factors",
        "type": "analytical",
        "specs": "Extract and analyze the risk factors disclosed by the company.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Categorization of Risks:\\n"
                "   - Operational, financial, strategic, legal/regulatory risks\\n"
                "   - Prioritization of key risks by the company\\n"
                "\\n"
                "b. Risk Mitigation:\\n"
                "   - Company's strategies to manage and mitigate key risks\\n"
                "   - Effectiveness of risk management practices\\n"
                "\\n"
                "c. Emerging Risks:\\n"
                "   - New or evolving risks on the horizon\\n"
                "   - Company's preparedness for future challenges\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 20,
        "title": "ESG Strategy",
        "type": "analytical",
        "specs": "Extract and analyze the company's Environmental, Social, and Governance (ESG) strategy.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. ESG Materiality:\\n"
                "   - Key ESG issues for the company and its industry\\n"
                "   - Alignment with stakeholder expectations\\n"
                "\\n"
                "b. ESG Integration:\\n"
                "   - Integration of ESG into corporate strategy and operations\\n"
                "   - Governance and oversight of ESG issues\\n"
                "\\n"
                "c. ESG Reporting & Disclosure:\\n"
                "   - Frameworks and standards used for ESG reporting\\n"
                "   - Transparency and quality of ESG disclosures\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 21,
        "title": "ESG Performance",
        "type": "analytical",
        "specs": "Extract and analyze the company's Environmental, Social, and Governance (ESG) performance metrics.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Environmental Performance:\\n"
                "   - Greenhouse gas (GHG) emissions\\n"
                "   - Energy and water consumption\\n"
                "   - Waste management and recycling\\n"
                "\\n"
                "b. Social Performance:\\n"
                "   - Employee health and safety\\n"
                "   - Diversity and inclusion\\n"
                "   - Community engagement and social impact\\n"
                "\\n"
                "c. Governance Performance:\\n"
                "   - Board diversity and independence\\n"
                "   - Executive compensation alignment\\n"
                "   - Business ethics and anti-corruption\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 22,
        "title": "R&D Activities",
        "type": "analytical",
        "specs": "Extract and analyze the company's Research and Development (R&D) activities.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. R&D Investment:\\n"
                "   - R&D spending as a percentage of revenue\\n"
                "   - Trends in R&D investment over time\\n"
                "\\n"
                "b. R&D Focus:\\n"
                "   - Key areas of R&D and innovation\\n"
                "   - Alignment with product roadmap and market trends\\n"
                "\\n"
                "c. R&D Productivity:\\n"
                "   - Patents, new products, and other R&D outputs\\n"
                "   - Return on R&D investment\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 23,
        "title": "M&A History",
        "type": "analytical",
        "specs": "Extract and analyze the company's history of Mergers and Acquisitions (M&A).\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Key Transactions:\\n"
                "   - List of major acquisitions and divestitures\\n"
                "   - Strategic rationale for each transaction\\n"
                "\\n"
                "b. Integration Success:\\n"
                "   - How well acquired businesses have been integrated\\n"
                "   - Synergies realized vs. expected\\n"
                "\\n"
                "c. M&A Strategy:\\n"
                "   - Company's approach to M&A and capital allocation\\n"
                "   - Future M&A pipeline and priorities\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 24,
        "title": "Legal & Regulatory",
        "type": "analytical",
        "specs": "Extract and analyze any significant legal or regulatory issues affecting the company.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Litigation:\\n"
                "   - Material pending lawsuits and legal proceedings\\n"
                "   - Potential financial and operational impact\\n"
                "\\n"
                "b. Regulatory Compliance:\\n"
                "   - Key regulations governing the company's industry\\n"
                "   - Compliance record and any pending investigations\\n"
                "\\n"
                "c. Lobbying & Political Activities:\\n"
                "   - Company's engagement with policymakers and regulators\\n"
                "   - Key public policy issues affecting the company\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 25,
        "title": "Recent News & Events",
        "type": "analytical",
        "specs": "Extract and analyze recent news and significant events related to the company.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Recent Developments:\\n"
                "   - Major product launches, contract wins, etc.\\n"
                "   - Key management changes or corporate announcements\\n"
                "\\n"
                "b. Media Coverage:\\n"
                "   - Key themes in recent media coverage\\n"
                "   - Analyst commentary and investor sentiment\\n"
                "\\n"
                "c. Market Reaction:\\n"
                "   - Stock price performance and market reaction to events\\n"
                "   - Changes in analyst ratings or price targets\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 26,
        "title": "Key Investment Thesis Points",
        "type": "analytical",
        "specs": "Synthesize the key points that would form a bull case for investing in the company.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Growth Drivers:\\n"
                "   - Secular trends and market opportunities\\n"
                "   - Company-specific growth initiatives\\n"
                "\\n"
                "b. Competitive Strengths:\\n"
                "   - Sustainable competitive advantages\\n"
                "   - Barriers to entry and market positioning\\n"
                "\\n"
                "c. Valuation Upside:\\n"
                "   - Potential for multiple expansion or earnings growth\\n"
                "   - Catalysts for value creation\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 27,
        "title": "Key Bear Case Points",
        "type": "analytical",
        "specs": "Synthesize the key points that would form a bear case for investing in the company.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Key Risks & Challenges:\\n"
                "   - Competitive threats and market disruption\\n"
                "   - Operational or execution risks\\n"
                "\\n"
                "b. Structural Headwinds:\\n"
                "   - Secular trends or industry challenges\\n"
                "   - Regulatory or macroeconomic risks\\n"
                "\\n"
                "c. Valuation Concerns:\\n"
                "   - High valuation multiples or unrealistic expectations\\n"
                "   - Potential for earnings disappointment\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 28,
        "title": "Valuation Summary",
        "type": "analytical",
        "specs": "Extract and analyze the company's valuation metrics.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Valuation Multiples:\\n"
                "   - P/E, P/S, P/B, EV/EBITDA\\n"
                "   - Historical valuation ranges\\n"
                "\\n"
                "b. Peer Comparison:\\n"
                "   - Valuation relative to key competitors\\n"
                "   - Justification for any valuation premium or discount\\n"
                "\\n"
                "c. Intrinsic Valuation:\\n"
                "   - Discounted Cash Flow (DCF) analysis\\n"
                "   - Sum-of-the-parts (SOTP) analysis\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 29,
        "title": "Analyst Ratings & PTs",
        "type": "analytical",
        "specs": "Extract and analyze analyst ratings and price targets for the company.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Consensus View:\\n"
                "   - Distribution of buy/hold/sell ratings\\n"
                "   - Consensus price target and upside potential\\n"
                "\\n"
                "b. Analyst Dispersion:\\n"
                "   - Range of analyst price targets\\n"
                "   - Key areas of disagreement among analysts\\n"
                "\\n"
                "c. Recent Changes:\\n"
                "   - Recent upgrades, downgrades, and initiations\\n"
                "   - Changes in price targets and earnings estimates\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 30,
        "title": " SWOT Analysis",
        "type": "analytical",
        "specs": "Conduct a SWOT (Strengths, Weaknesses, Opportunities, Threats) analysis for the company.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Strengths:\\n"
                "   - Internal capabilities that give the company an advantage\\n"
                "b. Weaknesses:\\n"
                "   - Internal factors that put the company at a disadvantage\\n"
                "c. Opportunities:\\n"
                "   - External factors that the company can exploit to its advantage\\n"
                "d. Threats:\\n"
                "   - External factors that could harm the company's performance\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 31,
        "title": "Company Outlook & Guidance",
        "type": "analytical",
        "specs": "Extract and analyze the company's outlook and guidance for future performance.\\n"
                "\\n"
                "Key areas to consider:\\n"
                "a. Management Guidance:\\n"
                "   - Key financial and operational metrics\\n"
                "   - Short-term and long-term targets\\n"
                "\\n"
                "b. Analyst Expectations:\\n"
                "   - Consensus estimates for revenue, earnings, etc.\\n"
                "   - Comparison of guidance vs. expectations\\n"
                "\\n"
                "c. Key Assumptions & Risks:\\n"
                "   - Underlying assumptions in the company's guidance\\n"
                "   - Key risks that could impact future performance\\n"
                "\\n"
                "For each data point, extract historical values for the last 3 years and the 5 most recent interim periods. "
                "Present data points in table format to the extent reasonable. If not, use bullet points.\\n"
                "For each data point, always try to identify the most recent value and its date, because that's usually the most important one.\\n"
                "For each data point, always reference the specific point in time or time period it relates to.\\n"
                "More recent data points (e.g. from subsequent interim financials) are more important than older data points (e.g. from the preceding annual report).\\n"
                "For each data point, note any anomalies, any disconnects between the data point and management's commentary, and any industry benchmarks mentioned."
                "Always include precise footnotes with exact sources, document references, page numbers, and sections for each data point."
    },
    {
        "number": 32,
        "title": "Data Book - Data Appendix",
        "type": "data_appendix",
        "specs": "This section is for data tables only. Extract all tables from the source documents and present them here.\\n"
                "\\n"
                "**CRITICAL INSTRUCTIONS:**\\n"
                "1. **DO NOT OMIT ANY DATA.** Your primary goal is to present ALL the numerical data provided in the input markdown. Do not summarize, aggregate, or drop any figures.\\n"
                "2. **Organize Logically:** Structure the appendix by grouping related tables under clear headings (e.g., Operational KPIs, Consolidated Financials, Segment Reporting).\\n"
                "3. **Combine Time Periods Intelligently:** Where possible, combine annual and quarterly data for the same metric into a single table. If this creates a confusing table, create separate clear tables instead. Never drop data to force a combination.\\n"
                "4. **Use Source Information:** Use page numbers and table titles from the original documents to inform your headings and groupings.\\n"
                "5. **NO NARRATIVE TEXT:** The final output for this section should contain ONLY: table headers, tables, and footnotes. REMOVE any analytical paragraphs, summaries, or other explanatory text."
    }
]